FROM centos
MAINTAINER Jerend Cao "bayonet_c1@163.com"

ENV BOOTPS_PORT=67/udp \
    BOOTPC_PORT=68/udp

USER root

RUN yum update -y; \
    yum install -y dhcp-server

RUN  mv /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf_bk
VOLUME ["/etc/dhcp/dhcpd.conf"]

EXPOSE $BOOTPS_PORT $BOOTPC_PORT

# Define default command.
CMD ["/usr/sbin/dhcpd", "-f -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid"]
